version: '3'
services:
  openvpn-xor:
    image: 'xmb5/docker-ovpn-xor'
    volumes:
      - './config:/config' # stores the server config file and all client configs
    cap_add:
      - 'NET_ADMIN'
    restart: 'always'
    ports:
      - '1194:1194/tcp' # outer:inner
    environment:
      - 'NUM_CLIENT_CONFIGS=25'
      - 'SCRAMBLE=0'
      - 'PUBLIC_ADDRESS=' # leave blank to automatically get public IPv4 address
      - 'PUBLIC_PORT=1194'
